version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xrp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: nestjs
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: xrp
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      NODE_ENV: production
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:?YOUTUBE_API_KEY is required}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID:?NAVER_CLIENT_ID is required}
      NAVER_CLIENT_SECRET_KEY: ${NAVER_CLIENT_SECRET_KEY:?NAVER_CLIENT_SECRET_KEY is required}
      X_BEARER_TOKEN: ${X_BEARER_TOKEN:?X_BEARER_TOKEN is required}
      CRYPTO_COMPARE: ${CRYPTO_COMPARE:?CRYPTO_COMPARE is required}
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
