name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd ~/app
            git pull origin master
            export CRYPTO_COMPARE='${{ secrets.CRYPTO_COMPARE }}'
            docker-compose config --quiet
            docker-compose down
            docker-compose up -d --build
